name: PHP Composer

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]


jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v2
        with:
         node-version: '12'

      - name: Validate composer.json and composer.lock
        run: composer validate

      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v2
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}

      - name: Install dependencies
        if: steps.composer-cache.outputs.cache-hit != 'true'
        run: composer install --ignore-platform-reqs --prefer-dist --no-progress --no-suggest

      - name: Install node
        run: npm install

      - name: Generate content
        run: |
          cd web
          pwd
          whoami
          ls -l . sites sites/default
          ../vendor/bin/drush -n --yes site:install
          ../vendor/bin/drush pm:enable devel devel_generate
          ../vendor/bin/drush devel-generate:content 10 --bundles=article
          ../vendor/bin/drush devel-generate:content 10 --bundles=page
          ../vendor/bin/drush pm:enable simple_sitemap
          ../vendor/bin/drush simple-sitemap:generate
          php -S localhost:8099 .ht.router.php &
          pa11y-ci -c ../.pa11yci
          curl http://localhost:8099/sitemap.xml | head -n 3 > map.xml
          printf '<url><loc>' >> map.xml
          ../vendor/bin/drush --uri=http://localhost:8099/ --no-browser uli / >>  map.xml
          echo '</url></loc>' >> map.xml
          curl http://localhost:8099/sitemap.xml |grep '^<url><loc>' >> map.xml
          echo '</urlset>' >> map.xml
          pa11y-ci -c ../.pa11yci --sitemap http://localhost:8099/map.xml
