name: PHP Composer

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]


jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v2
        with:
         node-version: '12'

      - name: Validate composer.json and composer.lock
        run: composer validate

#      - name: Cache Composer packages
#        id: composer-cache
#        uses: actions/cache@v2
#        with:
#          path: vendor
#          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
#          restore-keys: |
#            ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
#

      - name: Install dependencies
#        if: steps.composer-cache.outputs.cache-hit != 'true'
        run: composer install --ignore-platform-reqs --prefer-dist --no-progress --no-suggest

      - name: Install node
        run: npm install

      - name: Install Site and Generate content
        run: |
          cd web
          ../vendor/bin/drush -n --yes site:install
          ../vendor/bin/drush pm:enable devel devel_generate
          ../vendor/bin/drush devel-generate:content 10 --bundles=article
          ../vendor/bin/drush devel-generate:content 10 --bundles=page
          php -S localhost:8099 .ht.router.php 2>&1 > /dev/null &
          php ../scripts/spider.php > sites/default/files/map-source.xml

      - name: Scan Site as Anonymous
        run: |
          php scripts/spider.php > web/map-source.xml
          node_modules/.bin/pa11y-ci --sitemap http://localhost:8099/sites/default/files/map-source.xml || echo "Errors Found!"

      - name: Scan Site as Admin
        run: |
          head -n 1 web/sites/default/files/map-source.xml > web/sites/default/files/map.xml
          printf "<url><loc>%s</url></loc>\n" "$(vendor/bin/drush --uri=http://localhost:8099/ --no-browser uli /)" >> web/sites/default/files/map.xml
          grep '^ ' web/sites/default/files/map-source.xml >> web/sites/default/files/map.xml
          echo '</urlset>' >> web/sites/default/files/map.xml
          cat web/sites/default/files/map.xml
          node_modules/.bin/pa11y-ci --sitemap http://localhost:8099/sites/default/files/map.xml || echo "Errors Found!"
