name: PHP Composer

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v2
        with:
         node-version: '12'

      - name: Validate composer.json and composer.lock
        run: composer validate

      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v2
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}

      - name: Install dependencies
#        if: steps.composer-cache.outputs.cache-hit != 'true'
        run: composer install --ignore-platform-reqs --prefer-dist --no-progress --no-suggest

      - name: Install node
        run: npm install

      - name: Generate content
        run: |
          cd web
          pwd
          ls -l
          ../vendor/bin/drush -vvv -n --yes site:install standard
          ../vendor/bin/drush pm:enable devel devel_generate simple_sitemap sitemap
          ../vendor/bin/drush devel-generate:content 10 --bundles=article
          ../vendor/bin/drush devel-generate:content 10 --bundles=page
          ../vendor/vin/drush simple-sitemap:generate
          php -S localhost:8080 .ht.router.php &
          pa11y-ci -c ../.pa11yci --sitemap http://localhost:8080/sitemap.xml
